apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: music-pvc
  namespace: media

spec:
  accessModes:
    - ReadOnlyMany

  storageClassName: music
  resources:
    requests:
      storage: 100Gi
